language: node_js

sudo: false

addons:
    code_climate:
        repo_token: 2d863be68bcb16189cb10d0f68913a58ca0610c84e0427d45c6c5b6a0ced49e7 

node_js:
  - "6"
  - "4"

cache:
  directories:
    - node_modules
  
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov
  - npm install -g codeclimate-test-reporter
  
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  